spring.application.name=m-motors-backend

spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.info.env.enabled=true

info.app.name=M-Motors Backend
info.app.description=API backend de la plateforme M-Motors
info.app.version=0.0.1-SNAPSHOT

logging.level.com.keyd.mmotors=INFO
